# Path to root of this dir.
dotfiles_path: "<%= File.expand_path(File.dirname(__FILE__)) %>"

# Specify where symlinks will go (normally user's $HOME).
symlinks_path: "<%= ENV['HOME'] %>"

username: YOUR_USERNAME

# These paths will be chmodded
scripts: 
  git:           "git"
  scripts:       "scripts"

# Only files in this list will be symlinked.
symlinks:
  zshrc:         .zshrc
  zshenv:        .zshenv
  ackrc:         .ackrc
  gemrc:         .gemrc
  gitconfig:     .gitconfig
  gitignore:     .gitignore
  irbrc:         .irbrc
  railsrc:       .railsrc
  todo:          .todo
  ssh_config:    .ssh/config
  rdebugrc:      .rdebugrc
  rvmrc:         .rvmrc
  pryrc:         .pryrc

zsh:
  editor: 'mate -w' # or 'subl'
  theme: 'robbyrussell'

  vars:
    SOME_SHELL_VARIABLE: 'foo'

  plugins:
    - git
    - brew
    - bundler
    - autojump
    - cap
    - extract
    - gem
    - github
    - heroku
    - history-substring-search
    - lighthouse
    - node
    - npm
    - osx
    - thor

git:
  config:
    name: YOUR_NAME
    email: YOUR_EMAIL

github:
  user: YOUR_GITHUB_LOGIN
  token: YOUR_GITHUB_API_TOKEN

# Add personal gitignores here
gitignore:
  -

# Setup ssh config for enabling `ssh foo` type of shortcuts
ssh:
  - name: 'foo'
    host: 'foo.example.com'
    user: 'foo_user'
    identity: "<%= ENV['HOME'] %>/.ec2/foo"
    alive:
      interval: 30
      count: 120
